// This file is auto-generated by fetch_bids.py
// Do not edit manually. Last updated: 2026-02-02 18:25:30

window.GENERATED_BID_DATA = [
    {
        "title": "令和８年度兵庫県警察車両のタイヤ及びチューブの購入並びに兵庫県警察本部車両のタイヤ組替え及びパンク修理の単価契約",
        "category": "other",
        "agency": "国家公安委員会（警察庁）兵庫県警察",
        "date": "2026年2月6日",
        "date_iso": "2026-02-06",
        "url": "https://www.kkj.go.jp/d/?D=aHlvZ28vcG9saWNlX2h5b2dvLzIwMjYvMjAyNjAyMDZfMDMxNDAK&L=ja"
    },
    {
        "title": "兵庫県警察職員パソコン広告掲載事業",
        "category": "digital",
        "agency": "国家公安委員会（警察庁）兵庫県警察",
        "date": "2026年2月5日",
        "date_iso": "2026-02-05",
        "url": "https://www.kkj.go.jp/d/?D=aHlvZ28vcG9saWNlX2h5b2dvLzIwMjYvMjAyNjAyMDVfMDMxNTMK&L=ja"
    },
    {
        "title": "リアルタイム遠隔医療システム",
        "category": "digital",
        "agency": "国立大学法人岡山大学",
        "date": "2026年2月4日",
        "date_iso": "2026-02-04",
        "url": "https://www.kkj.go.jp/d/?D=b2theWFtYS9va2F5YW1hX3VfYWMvMjAyNi8yMDI2MDIwNF8wMDA2OQo=&L=ja"
    },
    {
        "title": "ウイルス対策ソフトウェアライセンスの納入",
        "category": "digital",
        "agency": "国家公安委員会（警察庁）兵庫県警察",
        "date": "2026年2月2日",
        "date_iso": "2026-02-02",
        "url": "https://www.kkj.go.jp/d/?D=aHlvZ28vcG9saWNlX2h5b2dvLzIwMjYvMjAyNjAyMDJfMDMxMzcK&L=ja"
    },
    {
        "title": "兵庫県警察学校柔道場及び剣道場空調設備整備工事",
        "category": "construction",
        "agency": "国家公安委員会（警察庁）兵庫県警察",
        "date": "2026年2月2日",
        "date_iso": "2026-02-02",
        "url": "https://www.kkj.go.jp/d/?D=aHlvZ28vcG9saWNlX2h5b2dvLzIwMjYvMjAyNjAyMDJfMDMxNTAK&L=ja"
    },
    {
        "title": "兵庫県警察本部交通機動隊庁舎等塵芥処理業務委託",
        "category": "service",
        "agency": "国家公安委員会（警察庁）兵庫県警察",
        "date": "2026年2月2日",
        "date_iso": "2026-02-02",
        "url": "https://www.kkj.go.jp/d/?D=aHlvZ28vcG9saWNlX2h5b2dvLzIwMjYvMjAyNjAyMDJfMDMxNDcK&L=ja"
    },
    {
        "title": "兵庫県警察本部姫路庁舎等塵芥処理業務委託",
        "category": "service",
        "agency": "国家公安委員会（警察庁）兵庫県警察",
        "date": "2026年2月2日",
        "date_iso": "2026-02-02",
        "url": "https://www.kkj.go.jp/d/?D=aHlvZ28vcG9saWNlX2h5b2dvLzIwMjYvMjAyNjAyMDJfMDMxNDYK&L=ja"
    },
    {
        "title": "兵庫県警察本部庁舎塵芥処理業務委託",
        "category": "service",
        "agency": "国家公安委員会（警察庁）兵庫県警察",
        "date": "2026年2月2日",
        "date_iso": "2026-02-02",
        "url": "https://www.kkj.go.jp/d/?D=aHlvZ28vcG9saWNlX2h5b2dvLzIwMjYvMjAyNjAyMDJfMDMxNDUK&L=ja"
    },
    {
        "title": "共焦点顕微鏡システムAX R 株式会社ニコン製 NSL-AX-SHR 1式",
        "category": "digital",
        "agency": "国立大学法人大阪大学",
        "date": "2026年1月31日",
        "date_iso": "2026-01-31",
        "url": "https://www.kkj.go.jp/d/?D=b3Nha2Evb3Nha2FfYWMvMjAyNi8yMDI2MDEzMV8wMDQ5Mwo=&L=ja"
    },
    {
        "title": "国頭岬灯台電源設備改良改修工事",
        "category": "construction",
        "agency": "海上保安庁第十管区海上保安本部",
        "date": "2026年1月31日",
        "date_iso": "2026-01-31",
        "url": "https://www.kkj.go.jp/d/?D=Z292Mi9rYWlob19tbGl0XzEwa2Fua3UvMjAyNi8yMDI2MDEzMV8wMDg1NQo=&L=ja"
    },
    {
        "title": "屋久島灯台機器改良改修工事",
        "category": "construction",
        "agency": "海上保安庁第十管区海上保安本部",
        "date": "2026年1月31日",
        "date_iso": "2026-01-31",
        "url": "https://www.kkj.go.jp/d/?D=Z292Mi9rYWlob19tbGl0XzEwa2Fua3UvMjAyNi8yMDI2MDEzMV8wMDg1NAo=&L=ja"
    },
    {
        "title": "深川市立病院医事業務委託（PDF:174KB）",
        "category": "service",
        "agency": "北海道深川市",
        "date": "2026年1月31日",
        "date_iso": "2026-01-31",
        "url": "https://www.kkj.go.jp/d/?D=aG9ra2FpZG8vZnVrYWdhd2FzaGkvMjAyNi8yMDI2MDEzMV8wMTE0OAo=&L=ja"
    },
    {
        "title": "令和８年度洗濯室業務委託",
        "category": "service",
        "agency": "独立行政法人労働者健康安全機構中国労災病院",
        "date": "2026年1月31日",
        "date_iso": "2026-01-31",
        "url": "https://www.kkj.go.jp/d/?D=aGlyb3NoaW1hL2NodWdva3Vfcm9zYWlfaG9zcGl0YWwvMjAyNi8yMDI2MDEzMV8wMDE1Nwo=&L=ja"
    },
    {
        "title": "令和８・９年度メッセンジャー業務委託",
        "category": "service",
        "agency": "独立行政法人労働者健康安全機構中国労災病院",
        "date": "2026年1月31日",
        "date_iso": "2026-01-31",
        "url": "https://www.kkj.go.jp/d/?D=aGlyb3NoaW1hL2NodWdva3Vfcm9zYWlfaG9zcGl0YWwvMjAyNi8yMDI2MDEzMV8wMDE1Ngo=&L=ja"
    },
    {
        "title": "令和８・９年度電話交換業務委託",
        "category": "service",
        "agency": "独立行政法人労働者健康安全機構中国労災病院",
        "date": "2026年1月31日",
        "date_iso": "2026-01-31",
        "url": "https://www.kkj.go.jp/d/?D=aGlyb3NoaW1hL2NodWdva3Vfcm9zYWlfaG9zcGl0YWwvMjAyNi8yMDI2MDEzMV8wMDE1NQo=&L=ja"
    },
    {
        "title": "デジタルX線画像診断装置保守",
        "category": "digital",
        "agency": "独立行政法人国立病院機構富山病院",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=dG95YW1hL3RveWFtYV9ob3NwLzIwMjYvMjAyNjAxMzBfMDAyNjEK&L=ja"
    },
    {
        "title": "据置型デジタル式汎用Ｘ 線透視診断装置",
        "category": "digital",
        "agency": "独立行政法人国立病院機構富山病院",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=dG95YW1hL3RveWFtYV9ob3NwLzIwMjYvMjAyNjAxMzBfMDAyNjAK&L=ja"
    },
    {
        "title": "【資エ庁】令和７年度経済産業省デジタルプラットフォーム構築事業（電気・ガス事業オンライン申請・届出システムに係る汎用申請機能の拡張）",
        "category": "digital",
        "agency": "経済産業省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA4OTYK&L=ja"
    },
    {
        "title": "【福岡森林管理署】福岡森林管理署デジタル複合機賃貸借契約及び保守契約",
        "category": "digital",
        "agency": "農林水産省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA4MDIK&L=ja"
    },
    {
        "title": "第１号物件 モノクロデジタル複合機賃貸借契約（根釧西部森林管理署事務室）",
        "category": "digital",
        "agency": "農林水産省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA4MDEK&L=ja"
    },
    {
        "title": "令和8年度空知森林管理署北空知支署デジタル複合機保守契約",
        "category": "digital",
        "agency": "農林水産省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA3NzkK&L=ja"
    },
    {
        "title": "【高知中部森林管理署】令和８年度 カラーデジタル複合機賃貸借・保守契約 1台",
        "category": "digital",
        "agency": "農林水産省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA2NTIK&L=ja"
    },
    {
        "title": "令和８年度コンビニエンスストアのデジタルサイネージを利用した電波利用環境保護等に関する広告業務の請負",
        "category": "digital",
        "agency": "総務省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA2MjIK&L=ja"
    },
    {
        "title": "＜事後審査型＞マイクロプラスチック同定・観察システム物品調達に係る条件付一般競争入札を実施します",
        "category": "digital",
        "agency": "佐賀県",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2FnYS9zYWdhX3ByZWYvMjAyNi8yMDI2MDEzMF8wMjI5OQo=&L=ja"
    },
    {
        "title": "入札公告「デジタル事例データベースの運用保守業務」に係る一般競争入札",
        "category": "digital",
        "agency": "独立行政法人情報処理推進機構",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=Z292L2lwYS8yMDI2LzIwMjYwMTMwXzAxMjcwCg==&L=ja"
    },
    {
        "title": "共焦点顕微鏡システム 一式",
        "category": "digital",
        "agency": "国立大学法人徳島大学",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=dG9rdXNoaW1hL3Rva3VzaGltYV91X2FjLzIwMjYvMjAyNjAxMzBfMDAwNzUK&L=ja"
    },
    {
        "title": "操作記録監査ソフトウェアライセンス購入及び保守 一式",
        "category": "digital",
        "agency": "科学技術振興機構様",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoMi9qc3QvMjAyNi8yMDI2MDEzMC00MV8yMDI1XzI4MAo=&L=ja"
    },
    {
        "title": "令和8年度経理システム運用支援・保守業務 一式",
        "category": "digital",
        "agency": "科学技術振興機構様",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoMi9qc3QvMjAyNi8yMDI2MDEzMC00MV8yMDI1XzI0Nwo=&L=ja"
    },
    {
        "title": "ウェブ会議サービス用ソフトウェアライセンスの供給 一式",
        "category": "digital",
        "agency": "法務省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA4OTMK&L=ja"
    },
    {
        "title": "セキュリティ情報統合分析ソフトウェアライセンス購入",
        "category": "digital",
        "agency": "国土交通省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA4ODUK&L=ja"
    },
    {
        "title": "令和８年度ソフトウェア（AutoCAD）外１点",
        "category": "digital",
        "agency": "国土交通省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA4MjcK&L=ja"
    },
    {
        "title": "消防庁衛星車載局車ヘリサット機器の修繕",
        "category": "digital",
        "agency": "総務省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjAzODQK&L=ja"
    },
    {
        "title": "防災気象情報システム改修業務",
        "category": "digital",
        "agency": "総務省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA1MzcK&L=ja"
    },
    {
        "title": "ノートパソコン購入",
        "category": "digital",
        "agency": "国立研究開発法人海上・港湾・航空技術研究所海上技術安全研究所",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=dG9reW8vbm1yaV9nby8yMDI2LzIwMjYwMTMwXzAwNjQyCg==&L=ja"
    },
    {
        "title": "「令和7年度第2回用途廃止パソコン及びプリンタ等の売却」における一般競争入札の実施について",
        "category": "digital",
        "agency": "大阪府八尾市",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=b3Nha2EveWFvX2NpdHkvMjAyNi8yMDI2MDEzMF8wMDQ5Mgo=&L=ja"
    },
    {
        "title": "中東及び北アフリカ地域におけるオール光ネットワーク技術の展開に向けた調査研究の請負",
        "category": "digital",
        "agency": "総務省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA1MDIK&L=ja"
    },
    {
        "title": "REDCapシステム運用支援業務 委託契約にかかる一般競争入札について",
        "category": "digital",
        "agency": "国立研究開発法人国立循環器病研究センター",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=b3Nha2EvbmN2Yy8yMDI2LzIwMjYwMTMwXzAxNDIxCg==&L=ja"
    },
    {
        "title": "電気調達に係る一般競争入札について（山梨県立北杜高等学校ほか３８施設）",
        "category": "education",
        "agency": "山梨県",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=eWFtYW5hc2hpL3lhbWFuYXNoaV9wcmVmLzIwMjYvMjAyNjAxMzBfMDA2NjIK&L=ja"
    },
    {
        "title": "海上保安学校ボイラー運転業務（総務 単契）",
        "category": "education",
        "agency": "国土交通省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA4NzcK&L=ja"
    },
    {
        "title": "海上保安学校宮城分校給食業務（宮校 単契）",
        "category": "education",
        "agency": "国土交通省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA4NzYK&L=ja"
    },
    {
        "title": "基町小学校屋内運動場大規模改修工事",
        "category": "education",
        "agency": "広島県広島市",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL2tlaXlha3VfaGlyb3NoaW1hX2NpdHkvMjAyNi8yMDI2MDEzMF8wMjYyMAo=&L=ja"
    },
    {
        "title": "【規制庁】令和８年度放射線測定及び放射線防護研修の実施",
        "category": "education",
        "agency": "環境省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjAzOTUK&L=ja"
    },
    {
        "title": "令和８年度前期免許証（医師等全13職種）及び臨床研修修了登録証（医師及び歯科医師）出力及び封入業務一式",
        "category": "education",
        "agency": "厚生労働省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA3NjEK&L=ja"
    },
    {
        "title": "外国要人との会談及 び国際研修等における通訳業務 一式",
        "category": "education",
        "agency": "法務省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA3NDcK&L=ja"
    },
    {
        "title": "サイバーセキュリティ研修の提供（２）",
        "category": "education",
        "agency": "国家公安委員会（警察庁）",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA3MjkK&L=ja"
    },
    {
        "title": "研修課程等実施業務委託 一式",
        "category": "education",
        "agency": "法務省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjAzNzkK&L=ja"
    },
    {
        "title": "2026-2027年度PCM研修業務（25a00737）（1.6MB）",
        "category": "education",
        "agency": "独立行政法人国際協力機構",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=Z292Ny9qaWNhX2dvLzIwMjYvMjAyNjAxMzBfMDAxNjUK&L=ja"
    },
    {
        "title": "【電子入札】【電子契約】原子力・エネルギーに関する教育支援に係る作業",
        "category": "education",
        "agency": "国立研究開発法人日本原子力研究開発機構敦賀",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=Z292L2phZWFfZ28vMjAyNi8yMDI2MDEzMF8wNDE5Nwo=&L=ja"
    },
    {
        "title": "入札公告第７号（６災農業集落排水事業管路復旧工事（倉垣地区１工区））",
        "category": "construction",
        "agency": "石川県志賀町",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=aXNoaWthd2Evc2hpa2FfdG93bi8yMDI2LzIwMjYwMjI2XzAwMjM1Cg==&L=ja"
    },
    {
        "title": "入札公告第６号（６災農業集落排水事業管路復旧工事（福井地区１工区）外１件（合併入札））",
        "category": "agriculture",
        "agency": "石川県志賀町",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=aXNoaWthd2Evc2hpa2FfdG93bi8yMDI2LzIwMjYwMjI2XzAwMjM0Cg==&L=ja"
    },
    {
        "title": "入札公告第５号（６災農業集落排水事業管路復旧工事（矢駄地区）外１件（合併入札））",
        "category": "agriculture",
        "agency": "石川県志賀町",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=aXNoaWthd2Evc2hpa2FfdG93bi8yMDI2LzIwMjYwMjI2XzAwMjMzCg==&L=ja"
    },
    {
        "title": "東条川二期農業水利事業所 広幅複合機１台賃貸借及び保守",
        "category": "agriculture",
        "agency": "農林水産省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA4MzMK&L=ja"
    },
    {
        "title": "鹿追地域農業開発事業所 機械警備業務",
        "category": "agriculture",
        "agency": "国土交通省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA1MjUK&L=ja"
    },
    {
        "title": "旭東農地整備事業 聖台西神楽４１南農区区画整理工事",
        "category": "agriculture",
        "agency": "国土交通省北海道開発局",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=aG9ra2FpZG8vaGtkX21saXRfZ29faG9uYnUvMjAyNi8yMDI2MDEzMF8wNzQ0Ngo=&L=ja"
    },
    {
        "title": "令和８年度食品循環資源の再生利用等の普及促進方策等検討業務[総合評価落札方式]",
        "category": "agriculture",
        "agency": "環境省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA4NTkK&L=ja"
    },
    {
        "title": "令和７年度輸出先国・地域における日本産農林水産物・食品の規制等への対応の強化委託事業",
        "category": "agriculture",
        "agency": "農林水産省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA4NTEK&L=ja"
    },
    {
        "title": "栄養食品類購入契約（ＣＺ—Ｈｉ ２００ 外95件）",
        "category": "agriculture",
        "agency": "独立行政法人国立病院機構三重中央医療センター",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=bWllL21pZV9jaHVvX2lyeW9fY2VudGVyLzIwMjYvMjAyNjAxMzBfMDAyNTUK&L=ja"
    },
    {
        "title": "特殊食品 CZ-Hi ﾊﾞｯｸﾞ 外15品目",
        "category": "agriculture",
        "agency": "独立行政法人国立病院機構呉医療センター",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=aGlyb3NoaW1hL2t1cmVfaXJ5b19jZW50ZXIvMjAyNi8yMDI2MDEzMF8wMDg0MAo=&L=ja"
    },
    {
        "title": "入札公告第11号（とぎ保育園災害復旧工事）",
        "category": "construction",
        "agency": "石川県志賀町",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=aXNoaWthd2Evc2hpa2FfdG93bi8yMDI2LzIwMjYwMjI2XzAwMjM5Cg==&L=ja"
    },
    {
        "title": "入札公告第10号（志賀町文化ホール震災復旧工事）",
        "category": "construction",
        "agency": "石川県志賀町",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=aXNoaWthd2Evc2hpa2FfdG93bi8yMDI2LzIwMjYwMjI2XzAwMjM4Cg==&L=ja"
    },
    {
        "title": "入札公告第９号（令和７・８年度志加浦配水池耐震化（改築・更新）工事（管理棟築造））",
        "category": "construction",
        "agency": "石川県志賀町",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=aXNoaWthd2Evc2hpa2FfdG93bi8yMDI2LzIwMjYwMjI2XzAwMjM3Cg==&L=ja"
    },
    {
        "title": "入札公告第８号（６災５１０８号・５１１１号公共下水道事業（富来処理区）管路復旧工事（富来３・４工区））",
        "category": "construction",
        "agency": "石川県志賀町",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=aXNoaWthd2Evc2hpa2FfdG93bi8yMDI2LzIwMjYwMjI2XzAwMjM2Cg==&L=ja"
    },
    {
        "title": "職員健康診断業務委託",
        "category": "service",
        "agency": "独立行政法人国立病院機構富山病院",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=dG95YW1hL3RveWFtYV9ob3NwLzIwMjYvMjAyNjAxMzBfMDAyNjIK&L=ja"
    },
    {
        "title": "（一般競争入札公告）三菱製エレベーター保守点検 一式",
        "category": "service",
        "agency": "国立研究開発法人医薬基盤・健康・栄養研究所国立健康・栄養研究所",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=dG9reW8vbmliaW9obl9nby8yMDI2LzIwMjYwMTMwXzAwNDI0Cg==&L=ja"
    },
    {
        "title": "令和８年度 東京航空貨物出張所及び麻薬探知犬訓練センター室清掃業務（PDF：142KB）",
        "category": "service",
        "agency": "財務省東京税関",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=dG9reW8vY3VzdG9tc190b2t5by8yMDI2LzIwMjYwMTMwXzAwODIxCg==&L=ja"
    },
    {
        "title": "令和８年度 新潟税関支署東港出張所清掃業務（PDF：141KB）",
        "category": "service",
        "agency": "財務省東京税関",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=dG9reW8vY3VzdG9tc190b2t5by8yMDI2LzIwMjYwMTMwXzAwODIwCg==&L=ja"
    },
    {
        "title": "令和８年度浜田法務合同庁舎、松江地方検察庁益田支部庁舎及び益田地方合同庁舎清掃等業務委託契約 (PDF形式 : 88KB)",
        "category": "service",
        "agency": "検察庁松江地方検察庁",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2hpbWFuZS9rZW5zYXRzdV9tYXRzdWUvMjAyNi8yMDI2MDEzMF8wMDAwMwo=&L=ja"
    },
    {
        "title": "令和８年度与那原維持出張所外２カ所庁舎清掃業務",
        "category": "service",
        "agency": "内閣府",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA5NDQK&L=ja"
    },
    {
        "title": "調達情報（令和８年度立川第二法務総合庁舎警備保安業務の入札に係る公告）",
        "category": "service",
        "agency": "検察庁東京地方検察庁",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=dG9reW8va2Vuc2F0c3VfdG9reW8vMjAyNi8yMDI2MDEzMF8wMDIzMgo=&L=ja"
    },
    {
        "title": "入札公告（令和８年度大津地方検察庁専用部分警備業務委託契約）",
        "category": "service",
        "agency": "検察庁大津地方検察庁",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2hpZ2Eva2Vuc2F0c3Vfb3RzdS8yMDI2LzIwMjYwMTMwXzAwMDIyCg==&L=ja"
    },
    {
        "title": "令和８年度藤沢労働総合庁舎外３施設における警備業務",
        "category": "service",
        "agency": "厚生労働省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA5NDUK&L=ja"
    },
    {
        "title": "令和8年度横浜港北地方合同庁舎外５施設における警備業務委託",
        "category": "service",
        "agency": "厚生労働省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA5NDMK&L=ja"
    },
    {
        "title": "令和８年度福島地方検察庁歳入金運搬警備業務委託契約",
        "category": "service",
        "agency": "法務省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA4OTIK&L=ja"
    },
    {
        "title": "令和８年度岩国飛行場交通誘導警備業務",
        "category": "service",
        "agency": "防衛省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA4NjkK&L=ja"
    },
    {
        "title": "令和８年度釧路湿原野生生物保護センターほか６施設の機械警備業務",
        "category": "service",
        "agency": "環境省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA4MjkK&L=ja"
    },
    {
        "title": "令和８年度 警備業務",
        "category": "service",
        "agency": "国土交通省",
        "date": "2026年1月30日",
        "date_iso": "2026-01-30",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMzBfNjA4MTgK&L=ja"
    },
    {
        "title": "消防団員ドローン操作講習（消防団ドローン・DX推進事業）業務委託",
        "category": "digital",
        "agency": "総務省",
        "date": "2026年1月29日",
        "date_iso": "2026-01-29",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMjlfNjAzMjgK&L=ja"
    },
    {
        "title": "サイエンスオリンピアド2026旅行手配、競技通訳手配等 一式",
        "category": "tourism",
        "agency": "科学技術振興機構様",
        "date": "2026年1月29日",
        "date_iso": "2026-01-29",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoMi9qc3QvMjAyNi8yMDI2MDEyOS00MV8yMDI1XzI2Ngo=&L=ja"
    },
    {
        "title": "学校給食食材調達業務委託に係る総合評価落札方式による一般競争入札の実施について",
        "category": "education",
        "agency": "大阪府箕面市",
        "date": "2026年1月29日",
        "date_iso": "2026-01-29",
        "url": "https://www.kkj.go.jp/d/?D=b3Nha2EvbWlub2hfY2l0eS8yMDI2LzIwMjYwMTI5XzAwMzM0Cg==&L=ja"
    },
    {
        "title": "令和８年度窓口DXの推進に向けた派遣型窓口BPRアドバイザー活用策に係る調査研究",
        "category": "digital",
        "agency": "デジタル庁\n東京都",
        "date": "2026年1月28日",
        "date_iso": "2026-01-28",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjYvMDEvMjAyNjAxMjhfNjAxNDMK&L=ja"
    },
    {
        "title": "（令和７年度）県立学校自動販売機設置事業による自動販売機設置事業者の募集について",
        "category": "education",
        "agency": "広島県",
        "date": "2026年1月28日",
        "date_iso": "2026-01-28",
        "url": "https://www.kkj.go.jp/d/?D=aGlyb3NoaW1hL2hpcm9zaGltYV9wcmVmLzIwMjYvMjAyNjAxMjhfMDU3NjUK&L=ja"
    },
    {
        "title": "令和8年度訓練教材用ガスの調達（長崎・佐世保） (PDF 158 KB)",
        "category": "education",
        "agency": "独立行政法人高齢・障害・求職者雇用支援機構長崎支部",
        "date": "2026年1月28日",
        "date_iso": "2026-01-28",
        "url": "https://www.kkj.go.jp/d/?D=Z292Ny9qZWVkX3NoaWJ1X25hZ2FzYWtpLzIwMjYvMjAyNjAxMjhfMDAxMDUK&L=ja"
    }
];
